// <auto-generated />
using System;
using ERP_backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_backend.Migrations
{
    [DbContext(typeof(QlySanXuatErpContext))]
    partial class QlySanXuatErpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_backend.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.AspNetUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUser", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.BaoCaoSanXuat", b =>
                {
                    b.Property<Guid>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("HieuSuatSanXuat")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(38, 20)")
                        .HasComputedColumnSql("([SoLuongSxThucTe]/[SoLuongSxMucTieu])", true);

                    b.Property<Guid>("MaKeHoach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoLuongSxMucTieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SoLuongSxThucTe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ThoiGianSanXuatKeHoach")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ThoiGianSanXuatThucTe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BaoCaoSa__25A9188CB9685144");

                    b.HasIndex(new[] { "MaKeHoach" }, "IX_BaoCaoSanXuat_MaKeHoach");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_BaoCaoSanXuat_MaSanPham");

                    b.ToTable("BaoCaoSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.BaoTri", b =>
                {
                    b.Property<Guid>("MaBaoTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaNhaMay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBaoTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaoTri")
                        .HasName("PK__BaoTri__51A9CA51196AB0A2");

                    b.HasIndex(new[] { "MaNhaMay" }, "IX_BaoTri_MaNhaMay");

                    b.ToTable("BaoTri", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.ChiPhiSanXuat", b =>
                {
                    b.Property<Guid>("MaChiPhiSanXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("LoaiChiPhi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MaLenh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaChiPhiSanXuat")
                        .HasName("PK__ChiPhiSa__5ECCCAAC3C8E922F");

                    b.HasIndex(new[] { "MaLenh" }, "IX_ChiPhiSanXuat_MaLenhSanXuat");

                    b.ToTable("ChiPhiSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.ChiTietDonHang", b =>
                {
                    b.Property<Guid>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("GiaSanPham")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("MaDonHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([SoLuong]*[GiaSanPham])", true);

                    b.HasKey("MaChiTietDonHang")
                        .HasName("PK__ChiTietD__4B0B45DD8CE891ED");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.ChiTietHoatDongSanXuat", b =>
                {
                    b.Property<Guid>("MaHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DieuKienBatDauGiaiDoanTiepTheo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("FileData")
                        .HasColumnType("VARBINARY(MAX)")
                        .HasColumnName("FileData");

                    b.Property<string>("GiaiDoanSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiTinhThoiGian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaQuyTrinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoLuongChoXuLy")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenHoatDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("ThoiGianMacDinh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaHoatDong")
                        .HasName("PK__ChiTietH__BD808BE7004BFB79");

                    b.HasIndex("MaQuyTrinh");

                    b.ToTable("ChiTietHoatDongSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.DinhMucNguyenVatLieu", b =>
                {
                    b.Property<Guid>("MaDinhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaNguyenVatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MucDoSuDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ThoiGianSanXuat")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaDinhMuc")
                        .HasName("PK__DinhMucN__DD5A07C3DD27862C");

                    b.HasIndex("MaNguyenVatLieu");

                    b.HasIndex("MaSanPham");

                    b.ToTable("DinhMucNguyenVatLieu", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.DonHang", b =>
                {
                    b.Property<Guid>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("MaKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584ADEF26CBBC");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.KeHoachSanXuat", b =>
                {
                    b.Property<Guid>("MaKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaNhaMay")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MucTonKhoAnToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("NgayBatDauDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayKetThucDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiChinhSua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SoLuongSanXuatToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SoLuongSanXuatToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKeHoach")
                        .HasName("PK__KeHoachS__88C5741F38AE5733");

                    b.HasIndex(new[] { "MaNhaMay" }, "IX_KeHoachSanXuat_MaNhaMay");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_KeHoachSanXuat_MaSanPham");

                    b.ToTable("KeHoachSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.KetQuaKiemTra", b =>
                {
                    b.Property<Guid>("KetQuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaKiemTra")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("KetQuaId")
                        .HasName("PK__KetQuaKi__0CFF0203736F27AC");

                    b.HasIndex("MaKiemTra");

                    b.ToTable("KetQuaKiemTra", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.Kho", b =>
                {
                    b.Property<Guid>("MaKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKho")
                        .HasName("PK__Kho__3BDA93507D65BBAD");

                    b.ToTable("Kho", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.KiemTraChatLuong", b =>
                {
                    b.Property<Guid>("MaKiemTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DoiKiemTra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiPhuTrach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKiemTra")
                        .HasName("PK__KiemTraC__5274B03138842E8E");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_KiemTraChatLuong_MaSanPham");

                    b.ToTable("KiemTraChatLuong", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.LenhGoBo", b =>
                {
                    b.Property<Guid>("MaLenhGoBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("LyDoGoBo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("MaKeHoach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiChiuTrachNhiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLenhGoBo")
                        .HasName("PK__LenhGoBo__A1B4B96BF7019010");

                    b.HasIndex(new[] { "MaKeHoach" }, "IX_LenhGoBo_MaKeHoach");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_LenhGoBo_MaSanPham");

                    b.ToTable("LenhGoBo", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.LenhSanXuat", b =>
                {
                    b.Property<Guid>("MaLenh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("KhuVucSanXuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MaDinhMuc")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaKeHoach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaQuyTrinh")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiChiuTrachNhiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLenh")
                        .HasName("PK__LenhSanX__7D94BAAF0BE9A0E5");

                    b.HasIndex(new[] { "MaKeHoach" }, "IX_LenhSanXuat_MaKeHoach");

                    b.HasIndex(new[] { "MaQuyTrinh" }, "IX_LenhSanXuat_MaQuyTrinh");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_LenhSanXuat_MaSanPham");

                    b.ToTable("LenhSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.NguyenVatLieu", b =>
                {
                    b.Property<Guid>("MaNguyenVatLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaVach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NhomNguyenVatLieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenNguyenVatLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("TonKhoToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TonKhoToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNguyenVatLieu")
                        .HasName("PK__NguyenVa__23D814DD4EC6C84A");

                    b.HasIndex(new[] { "MaVach" }, "UQ__NguyenVa__8BBF4A1C42550D8D")
                        .IsUnique()
                        .HasFilter("[MaVach] IS NOT NULL");

                    b.ToTable("NguyenVatLieu", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.NhaMay", b =>
                {
                    b.Property<Guid>("MaNhaMay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<int?>("ChiPhi")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NguoiQuanLy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhanLoai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaMay")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhaMay")
                        .HasName("PK__NhaMay__DE2FC056BA718C60");

                    b.ToTable("NhaMay", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.NhapKho", b =>
                {
                    b.Property<Guid>("MaNhapKho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayChinhSua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhapKho")
                        .HasName("PK__NhapKho__B060295071E49CD9");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_NhapKho_MaSanPham");

                    b.ToTable("NhapKho", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.QuyTrinhSanXuat", b =>
                {
                    b.Property<Guid>("MaQuyTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaHoatDong")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenQuyTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyTrinh")
                        .HasName("PK__QuyTrinh__EEEEC988E2013A6C");

                    b.ToTable("QuyTrinhSanXuat", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.SanPham", b =>
                {
                    b.Property<Guid>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaVach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhomSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442D3538263A");

                    b.HasIndex(new[] { "MaVach" }, "UQ__SanPham__8BBF4A1CB928F028")
                        .IsUnique()
                        .HasFilter("[MaVach] IS NOT NULL");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.SanPhamImg", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("ImgUrl")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("ImgURL");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId")
                        .HasName("PK__SanPhamI__7516F70CFEA084E8");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamImg", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.TonKho", b =>
                {
                    b.Property<Guid>("MaKho")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguyenVatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MucToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaKho", "MaNguyenVatLieu")
                        .HasName("PK__TonKho__F9E7121D8E758317");

                    b.HasIndex("MaNguyenVatLieu");

                    b.ToTable("TonKho", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.YeuCauNguyenVatLieu", b =>
                {
                    b.Property<Guid>("MaYeuCauNvl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaYeuCauNVL")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("MaKeHoach")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNguyenVatLieu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaNhaCungCap")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayGiaoHangDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoLuongCanThiet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiDonHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaYeuCauNvl")
                        .HasName("PK__YeuCauNg__BBF67A930EBB87E9");

                    b.HasIndex(new[] { "MaKeHoach" }, "IX_YeuCauNguyenVatLieu_MaKeHoach");

                    b.HasIndex(new[] { "MaNguyenVatLieu" }, "IX_YeuCauNguyenVatLieu_MaNguyenVqatLieu");

                    b.ToTable("YeuCauNguyenVatLieu", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ERP_backend.Models.BaoCaoSanXuat", b =>
                {
                    b.HasOne("ERP_backend.Models.KeHoachSanXuat", "MaKeHoachNavigation")
                        .WithMany("BaoCaoSanXuats")
                        .HasForeignKey("MaKeHoach")
                        .IsRequired()
                        .HasConstraintName("FK__BaoCaoSan__MaKeH__114A936A");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("BaoCaoSanXuats")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__BaoCaoSan__MaSan__123EB7A3");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.BaoTri", b =>
                {
                    b.HasOne("ERP_backend.Models.NhaMay", "MaNhaMayNavigation")
                        .WithMany("BaoTris")
                        .HasForeignKey("MaNhaMay")
                        .IsRequired()
                        .HasConstraintName("FK__BaoTri__MaNhaMay__7B5B524B");

                    b.Navigation("MaNhaMayNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.ChiPhiSanXuat", b =>
                {
                    b.HasOne("ERP_backend.Models.LenhSanXuat", "MaLenhNavigation")
                        .WithMany("ChiPhiSanXuats")
                        .HasForeignKey("MaLenh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiPhiSan__MaLen__00200768");

                    b.Navigation("MaLenhNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("ERP_backend.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK_ChiTietDonHang_DonHang");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK_ChiTietDonHang_SanPham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.ChiTietHoatDongSanXuat", b =>
                {
                    b.HasOne("ERP_backend.Models.QuyTrinhSanXuat", "MaQuyTrinhNavigation")
                        .WithMany("ChiTietHoatDongSanXuats")
                        .HasForeignKey("MaQuyTrinh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietHo__MaQuy__236943A5");

                    b.Navigation("MaQuyTrinhNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.DinhMucNguyenVatLieu", b =>
                {
                    b.HasOne("ERP_backend.Models.NguyenVatLieu", "MaNguyenVatLieuNavigation")
                        .WithMany("DinhMucNguyenVatLieus")
                        .HasForeignKey("MaNguyenVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__DinhMucNg__MaNgu__5AEE82B9");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("DinhMucNguyenVatLieus")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__DinhMucNg__MaSan__59FA5E80");

                    b.Navigation("MaNguyenVatLieuNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.DonHang", b =>
                {
                    b.HasOne("ERP_backend.Models.AspNetUser", "MaKhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_IdentityUser");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.KeHoachSanXuat", b =>
                {
                    b.HasOne("ERP_backend.Models.NhaMay", "MaNhaMayNavigation")
                        .WithMany("KeHoachSanXuats")
                        .HasForeignKey("MaNhaMay")
                        .IsRequired()
                        .HasConstraintName("FK__KeHoachSa__MaNha__5441852A");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("KeHoachSanXuats")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__KeHoachSa__MaSan__534D60F1");

                    b.Navigation("MaNhaMayNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.KetQuaKiemTra", b =>
                {
                    b.HasOne("ERP_backend.Models.KiemTraChatLuong", "MaKiemTraNavigation")
                        .WithMany("KetQuaKiemTras")
                        .HasForeignKey("MaKiemTra")
                        .IsRequired()
                        .HasConstraintName("FK__KetQuaKie__MaKie__7755B73D");

                    b.Navigation("MaKiemTraNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.KiemTraChatLuong", b =>
                {
                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("KiemTraChatLuongs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__KiemTraCh__MaSan__05D8E0BE");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.LenhGoBo", b =>
                {
                    b.HasOne("ERP_backend.Models.KeHoachSanXuat", "MaKeHoachNavigation")
                        .WithMany("LenhGoBos")
                        .HasForeignKey("MaKeHoach")
                        .IsRequired()
                        .HasConstraintName("FK__LenhGoBo__MaKeHo__76969D2E");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("LenhGoBos")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__LenhGoBo__MaSanP__778AC167");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.LenhSanXuat", b =>
                {
                    b.HasOne("ERP_backend.Models.KeHoachSanXuat", "MaKeHoachNavigation")
                        .WithMany("LenhSanXuats")
                        .HasForeignKey("MaKeHoach")
                        .IsRequired()
                        .HasConstraintName("FK__LenhSanXu__MaKeH__6C190EBB");

                    b.HasOne("ERP_backend.Models.QuyTrinhSanXuat", "MaQuyTrinhNavigation")
                        .WithMany("LenhSanXuats")
                        .HasForeignKey("MaQuyTrinh")
                        .IsRequired()
                        .HasConstraintName("FK__LenhSanXu__MaQuy__6D0D32F4");

                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("LenhSanXuats")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__LenhSanXu__MaSan__6E01572D");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaQuyTrinhNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.NhapKho", b =>
                {
                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("NhapKhos")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__NhapKho__MaSanPh__0B91BA14");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.SanPhamImg", b =>
                {
                    b.HasOne("ERP_backend.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamImgs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SanPhamIm__MaSan__49C3F6B7");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.TonKho", b =>
                {
                    b.HasOne("ERP_backend.Models.Kho", "MaKhoNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaKho")
                        .IsRequired()
                        .HasConstraintName("FK_TonKho_Kho");

                    b.HasOne("ERP_backend.Models.NguyenVatLieu", "MaNguyenVatLieuNavigation")
                        .WithMany("TonKhos")
                        .HasForeignKey("MaNguyenVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK_TonKho_NV");

                    b.Navigation("MaKhoNavigation");

                    b.Navigation("MaNguyenVatLieuNavigation");
                });

            modelBuilder.Entity("ERP_backend.Models.YeuCauNguyenVatLieu", b =>
                {
                    b.HasOne("ERP_backend.Models.KeHoachSanXuat", "MaKeHoachNavigation")
                        .WithMany("YeuCauNguyenVatLieus")
                        .HasForeignKey("MaKeHoach")
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauNgu__MaKeH__5FB337D6");

                    b.HasOne("ERP_backend.Models.NguyenVatLieu", "MaNguyenVatLieuNavigation")
                        .WithMany("YeuCauNguyenVatLieus")
                        .HasForeignKey("MaNguyenVatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__YeuCauNgu__MaNgu__60A75C0F");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaNguyenVatLieuNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ERP_backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ERP_backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ERP_backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERP_backend.Models.AspNetUser", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("ERP_backend.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("ERP_backend.Models.KeHoachSanXuat", b =>
                {
                    b.Navigation("BaoCaoSanXuats");

                    b.Navigation("LenhGoBos");

                    b.Navigation("LenhSanXuats");

                    b.Navigation("YeuCauNguyenVatLieus");
                });

            modelBuilder.Entity("ERP_backend.Models.Kho", b =>
                {
                    b.Navigation("TonKhos");
                });

            modelBuilder.Entity("ERP_backend.Models.KiemTraChatLuong", b =>
                {
                    b.Navigation("KetQuaKiemTras");
                });

            modelBuilder.Entity("ERP_backend.Models.LenhSanXuat", b =>
                {
                    b.Navigation("ChiPhiSanXuats");
                });

            modelBuilder.Entity("ERP_backend.Models.NguyenVatLieu", b =>
                {
                    b.Navigation("DinhMucNguyenVatLieus");

                    b.Navigation("TonKhos");

                    b.Navigation("YeuCauNguyenVatLieus");
                });

            modelBuilder.Entity("ERP_backend.Models.NhaMay", b =>
                {
                    b.Navigation("BaoTris");

                    b.Navigation("KeHoachSanXuats");
                });

            modelBuilder.Entity("ERP_backend.Models.QuyTrinhSanXuat", b =>
                {
                    b.Navigation("ChiTietHoatDongSanXuats");

                    b.Navigation("LenhSanXuats");
                });

            modelBuilder.Entity("ERP_backend.Models.SanPham", b =>
                {
                    b.Navigation("BaoCaoSanXuats");

                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DinhMucNguyenVatLieus");

                    b.Navigation("KeHoachSanXuats");

                    b.Navigation("KiemTraChatLuongs");

                    b.Navigation("LenhGoBos");

                    b.Navigation("LenhSanXuats");

                    b.Navigation("NhapKhos");

                    b.Navigation("SanPhamImgs");
                });
#pragma warning restore 612, 618
        }
    }
}
